(ns accurib.about)

(defn about-page []
  [:div.container
   [:div.flex.flex-column
    [:div.col-12
     [:img.fit {:src "/img/mcrib.png"}]
     [:p.mb2 "Countless commentaries from McRib advocates and detractors alike have led to great deal of misunderstanding surrounding the topic of what conditions may lead to an increase or a decrease of the emergence of a McRib sales event."]
     [:p.mb2 "This issue is of critical importance for the countless McRib advocates. Some would even argue that the intermittant reintroduction of McRib’s inimitable flavors creates a kind of psychosomatic dependency which can lead to addiction, depression, or even increased risk of suicide."]
     [:p.mb2 "For these reasons this team found it both a personal and humanitarian imperative to restore a semblance of power to consumers by clearing, if only by deduction, some degree the cloud of ignorance that keeps the mass of American McRib consumers at the mercy of faceless executives residing beneath the golden arches."]
     [:p.mb2 "First, a literature survey is in order. Our team reviewed prominent literature on the subject that spanned the first-hand accounts of the forgotten man to well-documented articles in prestigious journals that receive national acclaim. It quickly became apparent that although all parties agreed on the need to bring more transparency to the matter, the camps were firmly divided by whether the decision followed the steely logic of supply-side or demand-side economics. Too much to bear was the imagination that some heartless beaurocrat reclining at a bar outside the McDonald’s San Diego HQ could decide such a thing on a whim after a few stiff Martini’s. No, there had to be a reason, a grand plan governing it that our community could somehow master to its own advantage, much like the gambling addict is convinced that this time, at long last, he has discovered the ‘inside tip’ which will lead to certain riches at the slot machine."]
     [:p.mb2 "McDonald’s San Diego HQ could decide such a thing on a whim after a few stiff Martini’s. No, there had to be a reason, a grand plan governing it that our community could somehow master to its own advantage, much like the gambling addict is convinced that this time, at long last, he has discovered the ‘inside tip’ which will lead to certain riches at the slot machine."]
     [:p.mb2 "It has been passionately argued that the emergence of the McRib could be reduced to commodity prices - neglecting that McRibs are almost never released nationally, only locally. It has been suggested that McRibs are only released to prop up some monthly sales, ignoring the uncanny conflation of pork prices and regional peculiarities of the areas in which McRibs flourish. It has been argued that McRibs aren’t even profitable and will soon be relegated to the annals of history, yet millions of consumers line up every time the McRib emerges and even you yourself have found the matter so fascinating as to read this far."]
     [:p.mb2 "Regardless of the risk that such talk is only furthering this community in its McRib dependence, we did find that there would be some agreement when the data was viewed from the position of an impartial observer. And, we hope, by laying the data clearly before our community we can create a system whereby our thesis can be tested with actual data. In time, it may be possible to further refine this model so as to eliminate nearly all perceptible uncertainty from the McRib matter altogether; and that, we feel, is a very worthy goal in service of mankind."]
     [:p.mb2.bold "Thesis:"]
     [:p.mb2 "A combination of supply and demand forces converge to enable the emergence of the McRib sandwich and the McRib is never more likely to emerge than when conditions most closely resemble its most hospitable natural habitat: post-war Germany."]
     [:p.mb2 "Germany is the world’s highest consumer of pork per capita among the top 10 global economies. It boasts the world’s fourth-largest economy, a healthy per capita income, well-functioning cities, impressive logistics and transportation infrastructure, and a somewhat homogenous culture united in its enthusiasm for the McRib sandwich."]
     [:p.mb2 "First, demand:"]
     [:p.mb2 "Demand must be high for pork-derivative product, which can be measured in per capita pork consumption."]
     [:p.mb2 "Also, the region in which McRib is offered should have the means of easily purchasing a large number of the sandwiches, which can be measured as a function of the region’s per capita GDP and population density."]
     [:p.mb2 "McDonalds has the advantage of holding years of data on which stores have sold exactly how many of the 500 million McRibs that have been sold since its introduction. As a stand-in, however, we will have to accept the above proxy for that data."]
     [:p.bold.mb2 "Second, supply:"]
     [:p.mb2 "Although pork is only a small amount of McDonald’s meat purchase each year, the fact remains that this is still a significant amount for the US pork market. Although it has been suggested by some that McDonald’s releases McRib’s to capitalize on dropping pork prices in an effort to turn an opportunistic profit, the writers of this publication cannot take such a simplistic stance."]
     [:p.mb2 "Rather, it is the huge pull of the McDonald’s McRib industrial complex (note: originally created by the US Army source: https://www.vox.com/2015/8/4/9090961/mcrib-invented-army) that actually causes the sharp SPIKE in pork commodity prices, thereby requiring that pork already be on the decline before it becomes even possible to purchase requisite amount of pork inputs so as to achieve even a limited McRib release."]
     [:p.bold.mb2 "Finally, the commercial component:"]
     [:p.mb2 "Some reputable sources with information close to the matter have suggested that the McRib is actually a loss-leader and is used to drive purchase of auxillary products. That may well be the case, but of course there is no need for McDonalds to lead with a loss if they can lead with a profit margin as is done on all of their other meat-derived products. Rather, the simple commercial logic is that the McRib is always marginally popular in areas in which it is marginally popular; and, since it is released for short, unpredictable time periods it creates a kind of buzz that is guaranteed to pick up some extra revenue. Therefore, when revenue prospects in a region are looking a bit weak for the season, or when the fiscal year is coming to a close and a little bit of window-dressing for the company’s yearly earnings/share would do the shareholders well, the McRib is a natural choice."]
     [:p.mb2 "These factors, working together in union, make the basis for rational McRib release information. We hope that you will peruse the data and methodology released here, compare it over time with actual McRib releases, and further contribute to the project for the betterment of our McRib community, and mankind as a whole."]
     ]]])